apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-sandbox-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/lahavrud/rs-recruiting.git
      targetRevision: main
      path: helm/backend
      helm:
        valueFiles:
          - $values/envs/sandbox-dev/backend-values.yaml
    - repoURL: https://github.com/lahavrud/rs-recruiting-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
